version: "3"

services:

    redis:
        image: redis
        container_name: redis
        ports:
            - "6379:6379"
        networks:
            - gateway

    mongo:
        image: mongo:3
        container_name: mongo
        command: mongod --smallfiles --bind_ip_all
        volumes:
            - ./data:/data/db
        ports:
            - "27017:27017"
        networks:
            - gateway

    gateway:
        image: shipyardsuite/gateway:develop
        container_name: gateway
        ports:
            - "8080:8080"
            - "80:80"
            - "8443:8443"
            - "9876:9876"
        volumes:
            - ./gateway/config/system.config.yml:/usr/src/app/config/system.config.yml
            - ./gateway/config/gateway.config.yml:/usr/src/app/config/gateway.config.yml
        networks:
            - gateway

    homepage:
        image: shipyardsuite/homepage:develop
        command: sh -c 'npm run start'
        container_name: homepage
        ports:
            - "3001:3001"
        networks:
            - gateway
        environment:
            SERVICE_NAME: homepage
            SERVICE_PORT: 3001

    auth:
        image: shipyardsuite/auth:develop
        command: sh -c 'npm run start'
        container_name: auth
        ports:
            - "3002:3002"
        networks:
            - gateway
        environment:
            SERVICE_NAME: auth
            SERVICE_PORT: 3002

    player:
        image: shipyardsuite/player:develop
        command: sh -c 'npm run start'
        container_name: player
        ports:
            - "3006:3006"
        networks:
            - gateway
        environment:
            SERVICE_NAME: player
            SERVICE_PORT: 3006

    project:
        image: shipyardsuite/project:develop
        command: sh -c 'npm run start'
        container_name: project
        ports:
            - "3007:3007"
        networks:
            - gateway
        environment:
            SERVICE_NAME: project
            SERVICE_PORT: 3007

    user:
        image: shipyardsuite/user:develop
        command: sh -c 'npm run start'
        container_name: user
        ports:
            - "3009:3009"
        networks:
            - gateway
        environment:
            SERVICE_NAME: user
            SERVICE_PORT: 3009

    dashboard:
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - ./:/usr/src/app
        working_dir: /usr/src/app
        command: sh -c 'npm install; npm run start:dev'
        container_name: dashboard
        ports:
            - "3004:3004"
        networks:
            - gateway
        environment:
            SERVICE_NAME: dashboard
            SERVICE_PORT: 3004

networks:
    gateway:
