http:
    port: 8080
admin:
    port: 9876
    host: localhost
apiEndpoints:
    homepage:
        host: localhost
        paths: [ '/homepage/*', '/homepage/api/*']
    dashboard:
        host: localhost
        paths: [ '/dashboard/*', '/dashboard/api/*']
    notfound:
        host: localhost
        paths: [ '/notfound/*' ]
serviceEndpoints:
    homepage:
        url: 'http://homepage:5000'
    dashboard:
        url: 'http://dashboard:4000'
    notfound:
        url: 'http://notfound:3003'
policies:
    - basic-auth
    - cors
    - expression
    - key-auth
    - log
    - oauth2
    - proxy
    - rate-limit
pipelines:
    homepage:
        apiEndpoints:
            - homepage
        policies:
            - proxy:
                - action:
                    serviceEndpoint: homepage 
                    changeOrigin: true
    dashboard:
        apiEndpoints:
            - dashboard
        policies:
            - proxy:
                - action:
                    serviceEndpoint: dashboard 
                    changeOrigin: true
    notfound:
        apiEndpoints:
            - notfound
        policies:
            - proxy:
                - action:
                    serviceEndpoint: notfound 
                    changeOrigin: true
